# Generated by Django 2.0.7 on 2018-07-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='标题', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='intro',
            field=models.CharField(default='描述', max_length=100),
        ),
    ]
